version: '3.3'

services:
  api:
    container_name: basketball_api
    build: ./api-service
    restart: always
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=db
    volumes:
      - ./api-service/api:/app/api
  db:
    image: mysql:latest
    container_name: basketball_db
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=skFgWDDaUqc4viozYLqmoEVU
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=mydb
      - MYSQL_PASSWORD=3QgHYfFNcfbyhMyTnMKkxUwm


